# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the BSD license found in the
# LICENSE file in the root directory of this source tree.


import os
import warnings
import math
import torch
import torch.nn as nn
import torchvision
import torch.nn.functional as F
import torch.utils.checkpoint as checkpoint
from distutils.version import LooseVersion
from torch.nn.modules.utils import _pair, _single
import numpy as np
from functools import reduce, lru_cache
from operator import mul
from einops import rearrange
from einops.layers.torch import Rearrange


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            'mean is more than 2 std from [a, b] in nn.init.trunc_normal_. '
            'The distribution of values may be incorrect.',
            stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        low = norm_cdf((a - mean) / std)
        up = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [low, up], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * low - 1, 2 * up - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution.

    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py

    The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.

    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value

    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


def drop_path(x, drop_prob: float = 0., training: bool = False):
    """Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/drop.py
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0], ) + (1, ) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = keep_prob + torch.rand(shape, dtype=x.dtype, device=x.device)
    random_tensor.floor_()  # binarize
    output = x.div(keep_prob) * random_tensor
    return output


class DropPath(nn.Module):
    """Drop paths (Stochastic Depth) per sample  (when applied in main path of residual blocks).
    From: https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/drop.py
    """

    def __init__(self, drop_prob=None):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training)


def window_partition(x, window_size):
    """ Partition the input into windows. Attention will be conducted within the windows.

    Args:
        x: (B, D, H, W, C)
        window_size (tuple[int]): window size

    Returns:
        windows: (B*num_windows, window_size*window_size, C)
    """
    B, D, H, W, C = x.shape
    x = x.view(B, D // window_size[0], window_size[0], H // window_size[1], window_size[1], W // window_size[2],
               window_size[2], C)
    windows = x.permute(0, 1, 3, 5, 2, 4, 6, 7).contiguous().view(-1, reduce(mul, window_size), C)

    return windows


def window_reverse(windows, window_size, B, D, H, W):
    """ Reverse windows back to the original input. Attention was conducted within the windows.

    Args:
        windows: (B*num_windows, window_size, window_size, C)
        window_size (tuple[int]): Window size
        H (int): Height of image
        W (int): Width of image

    Returns:
        x: (B, D, H, W, C)
    """
    x = windows.view(B, D // window_size[0], H // window_size[1], W // window_size[2], window_size[0], window_size[1],
                     window_size[2], -1)
    x = x.permute(0, 1, 4, 2, 5, 3, 6, 7).contiguous().view(B, D, H, W, -1)

    return x


def get_window_size(x_size, window_size, shift_size=None):
    """ Get the window size and the shift size """

    use_window_size = list(window_size)
    if shift_size is not None:
        use_shift_size = list(shift_size)
    for i in range(len(x_size)):
        if x_size[i] <= window_size[i]:
            use_window_size[i] = x_size[i]
            if shift_size is not None:
                use_shift_size[i] = 0

    if shift_size is None:
        return tuple(use_window_size)
    else:
        return tuple(use_window_size), tuple(use_shift_size)


@lru_cache()
def compute_mask(D, H, W, window_size, shift_size, device):
    """ Compute attnetion mask for input of size (D, H, W). @lru_cache caches each stage results. """

    img_mask = torch.zeros((1, D, H, W, 1), device=device)  # 1 Dp Hp Wp 1
    cnt = 0
    for d in slice(-window_size[0]), slice(-window_size[0], -shift_size[0]), slice(-shift_size[0], None):
        for h in slice(-window_size[1]), slice(-window_size[1], -shift_size[1]), slice(-shift_size[1], None):
            for w in slice(-window_size[2]), slice(-window_size[2], -shift_size[2]), slice(-shift_size[2], None):
                img_mask[:, d, h, w, :] = cnt
                cnt += 1
    mask_windows = window_partition(img_mask, window_size)  # nW, ws[0]*ws[1]*ws[2], 1
    mask_windows = mask_windows.squeeze(-1)  # nW, ws[0]*ws[1]*ws[2]
    attn_mask = mask_windows.unsqueeze(1) - mask_windows.unsqueeze(2)
    attn_mask = attn_mask.masked_fill(attn_mask != 0, float(-100.0)).masked_fill(attn_mask == 0, float(0.0))

    return attn_mask


class Upsample(nn.Sequential):
    """Upsample module for video SR.

    Args:
        scale (int): Scale factor. Supported scales: 2^n and 3.
        num_feat (int): Channel number of intermediate features.
    """

    def __init__(self, scale, num_feat):
        assert LooseVersion(torch.__version__) >= LooseVersion('1.8.1'), \
            'PyTorch version >= 1.8.1 to support 5D PixelShuffle.'

        class Transpose_Dim12(nn.Module):
            """ Transpose Dim1 and Dim2 of a tensor."""

            def __init__(self):
                super().__init__()

            def forward(self, x):
                return x.transpose(1, 2)

        m = []
        if (scale & (scale - 1)) == 0:  # scale = 2^n
            for _ in range(int(math.log(scale, 2))):
                m.append(nn.Conv3d(num_feat, 4 * num_feat, kernel_size=(1, 3, 3), padding=(0, 1, 1)))
                m.append(Transpose_Dim12())
                m.append(nn.PixelShuffle(2))
                m.append(Transpose_Dim12())
                m.append(nn.LeakyReLU(negative_slope=0.1, inplace=True))
            m.append(nn.Conv3d(num_feat, num_feat, kernel_size=(1, 3, 3), padding=(0, 1, 1)))
        elif scale == 3:
            m.append(nn.Conv3d(num_feat, 9 * num_feat, kernel_size=(1, 3, 3), padding=(0, 1, 1)))
            m.append(Transpose_Dim12())
            m.append(nn.PixelShuffle(3))
            m.append(Transpose_Dim12())
            m.append(nn.LeakyReLU(negative_slope=0.1, inplace=True))
            m.append(nn.Conv3d(num_feat, num_feat, kernel_size=(1, 3, 3), padding=(0, 1, 1)))
        else:
            raise ValueError(f'scale {scale} is not supported. ' 'Supported scales: 2^n and 3.')
        super(Upsample, self).__init__(*m)

def inference_with_fusion_weight_bias2(x, weight1, bias1, weight2, bias2):
    weight = weight1.data + weight2.data
    bias = bias1.data + bias2.data
    y = F.linear(x, weight, bias)
    
    return y


class Mlp_GEGLU(nn.Module):
    """ Multilayer perceptron with gated linear unit (GEGLU). Ref. "GLU Variants Improve Transformer".

    Args:
        x: (B, D, H, W, C)

    Returns:
        x: (B, D, H, W, C)
    """

    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features

        self.fc11 = nn.Linear(in_features, hidden_features)
        self.fc12 = nn.Linear(in_features, hidden_features)
        self.act = act_layer()
        self.fc2 = nn.Linear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x):
        #print(x.shape)
        x = inference_with_fusion_weight_bias2(x, self.fc11.weight, self.fc11.bias, self.fc12.weight, self.fc12.bias)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x)

        return x


class WindowAttention(nn.Module):

    def __init__(self, dim, window_size, num_heads, qkv_bias=False, qk_scale=None, mut_attn=True, lo_ratio=0.5, hi_ratio=1, g_ratio=0.5):
        super().__init__()
        self.dim = dim
        self.window_size = window_size
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5
        self.mut_attn = mut_attn
        self.lo_ratio = lo_ratio
        self.lo_heads = int(self.num_heads*lo_ratio)
        self.lo_dim = self.lo_heads*head_dim
        self.hi_ratio = hi_ratio
        self.hi_heads = int(self.num_heads*hi_ratio)
        self.hi_dim = self.hi_heads*head_dim
        self.g_ratio = g_ratio
        self.g_heads = int(self.num_heads*g_ratio)
        self.g_dim = self.g_heads*head_dim

        # self attention with relative position bias
        self.relative_position_bias_table_hi = nn.Parameter(
            torch.zeros((2 * window_size[0] - 1) * (2 * window_size[1] - 1) * (2 * window_size[2] - 1),
                        self.hi_heads))  # 2*Wd-1 * 2*Wh-1 * 2*Ww-1, nH
        self.relative_position_bias_table_lo = nn.Parameter(
            torch.zeros((2 * window_size[0] - 1) * (2 * window_size[1] - 1) * (2 * window_size[2] - 1),
                        self.lo_heads))  # 2*Wd-1 * 2*Wh-1 * 2*Ww-1, nH
        self.relative_position_bias_table_g = nn.Parameter(
            torch.zeros((2 * window_size[0] - 1) * (2 * window_size[1] - 1) * (2 * window_size[2] - 1),
                        self.g_heads))  # 2*Wd-1 * 2*Wh-1 * 2*Ww-1, nH
        self.register_buffer("relative_position_index", self.get_position_index(window_size))
        self.hi_qkv_self = nn.Linear(dim, self.hi_dim * 3, bias=qkv_bias)
        self.lo_q_self = nn.Linear(dim, self.lo_dim, bias=qkv_bias)
        self.lo_kv_self = nn.Linear(dim, self.lo_dim * 2, bias=qkv_bias)
        self.g_q_self = nn.Linear(dim, self.g_dim, bias=qkv_bias)
        self.g_kv_self = nn.Linear(dim, self.g_dim * 2, bias=qkv_bias)
        self.sr = nn.AvgPool2d(kernel_size=2, stride=2)
        self.fusion = nn.Linear(self.lo_dim+self.hi_dim+self.g_dim, dim)
        self.proj = nn.Linear(dim, dim)

        # mutual attention with sine position encoding
        if self.mut_attn:
            self.register_buffer("position_bias",
                                 self.get_sine_position_encoding(window_size[1:], dim // 2, normalize=True))
            self.hi_qkv_mut = nn.Linear(dim, self.hi_dim * 3, bias=qkv_bias)
            self.g_q_mut = nn.Linear(dim, self.g_dim, bias=qkv_bias)
            self.g_kv_mut = nn.Linear(dim, self.g_dim * 2, bias=qkv_bias)
            self.proj = nn.Linear(dim+self.hi_dim+self.g_dim, dim)

        self.softmax = nn.Softmax(dim=-1)
        trunc_normal_(self.relative_position_bias_table_hi, std=.02)
        trunc_normal_(self.relative_position_bias_table_lo, std=.02)
        trunc_normal_(self.relative_position_bias_table_g, std=.02)

    def forward(self, x, x_resize, mask=None):

        B_, N, C = x.shape

        hi_qkv = self.hi_qkv_self(x).reshape(B_, N, 3, self.hi_heads, self.hi_dim // self.hi_heads).permute(2, 0, 3, 1, 4)
        hi_q, hi_k, hi_v = hi_qkv[0], hi_qkv[1], hi_qkv[2]  # B_, nH, N, C
        x_out_hi = self.hi_attention(hi_q, hi_k, hi_v, mask, (B_, N, self.hi_dim), relative_position_encoding=True)

        lo_q = self.lo_q_self(x).reshape(B_, N, 1, self.lo_heads, self.lo_dim // self.lo_heads).permute(2, 0, 3, 1, 4)
        _, ws1, ws2 = self.window_size
        ws0 = N//ws1//ws2
        x_reshaped = x.clone().reshape(B_, ws0, ws1, ws2, C).reshape(-1, ws1, ws2, C).permute(0, 3, 1, 2)
        x_d2 = self.sr(x_reshaped).reshape(-1, C, ws1//2, ws2//2).permute(0, 2, 3, 1)
        x_d2 = x_d2.reshape(B_, ws0, ws1//2, ws2//2, C).reshape(B_, N//4, C)
        lo_kv = self.lo_kv_self(x_d2).reshape(B_, N//4, 2, self.lo_heads, self.lo_dim // self.lo_heads).permute(2, 0, 3, 1, 4)
        lo_q, lo_k, lo_v = lo_q[0], lo_kv[0], lo_kv[1]
        x_out_lo = self.lo_attention(lo_q, lo_k, lo_v, mask, (B_, N, self.lo_dim), relative_position_encoding=True)

        g_q = self.g_q_self(x).reshape(B_, N, 1, self.lo_heads, self.lo_dim // self.lo_heads).permute(2, 0, 3, 1, 4)
        g_kv = self.g_kv_self(x_resize).reshape(B_, N, 2, self.g_heads, self.g_dim // self.g_heads).permute(2, 0, 3, 1, 4)
        g_q, g_k, g_v = g_q[0], g_kv[0], g_kv[1]
        x_out_g = self.g_attention(g_q, g_k, g_v, mask, (B_, N, self.g_dim), relative_position_encoding=True)
        x_out = torch.cat([x_out_hi, x_out_lo, x_out_g], 2)
        x_out = self.fusion(x_out)
        
        if self.mut_attn:
            x_new = x + self.position_bias.repeat(1, 2, 1)
            hi_qkv = self.hi_qkv_mut(x_new).reshape(B_, N, 3, self.hi_heads, self.hi_dim // self.hi_heads).permute(2, 0, 3, 1, 4)
            (hi_q1, hi_q2), (hi_k1, hi_k2), (hi_v1, hi_v2) = torch.chunk(hi_qkv[0], 2, dim=2), torch.chunk(hi_qkv[1], 2, dim=2), torch.chunk(hi_qkv[2], 2, dim=2)  # B_, nH, N/2, C
            x1_aligned_hi = self.hi_attention(hi_q2, hi_k1, hi_v1, mask, (B_, N // 2, self.hi_dim), relative_position_encoding=False)
            x2_aligned_hi = self.hi_attention(hi_q1, hi_k2, hi_v2, mask, (B_, N // 2, self.hi_dim), relative_position_encoding=False)
            x_resize_new = x_resize + self.position_bias.repeat(1, 2, 1)
            g_q = self.g_q_mut(x_new).reshape(B_, N, 1, self.g_heads, self.g_dim // self.g_heads).permute(2, 0, 3, 1, 4)
            g_kv = self.g_kv_mut(x_resize_new).reshape(B_, N, 2, self.g_heads, self.g_dim // self.g_heads).permute(2, 0, 3, 1, 4)
            (g_q1, g_q2), (g_k1, g_k2), (g_v1, g_v2) = torch.chunk(g_q[0], 2, dim=2), torch.chunk(g_kv[0], 2, dim=2), torch.chunk(g_kv[1], 2, dim=2)
            x1_aligned_g = self.g_attention(g_q2, g_k1, g_v1, mask, (B_, N // 2, self.g_dim), relative_position_encoding=False)
            x2_aligned_g = self.g_attention(g_q1, g_k2, g_v2, mask, (B_, N // 2, self.g_dim), relative_position_encoding=False)

            x1_aligned = torch.cat([x1_aligned_hi, x1_aligned_g], 2)
            x2_aligned = torch.cat([x2_aligned_hi, x2_aligned_g], 2)
            x_out = torch.cat([torch.cat([x1_aligned, x2_aligned], 1), x_out], 2)

        # projection
        x = self.proj(x_out)

        return x

    def hi_attention(self, q, k, v, mask, x_shape, relative_position_encoding=True):
        B_, N, C = x_shape
        attn = (q * self.scale) @ k.transpose(-2, -1)

        if relative_position_encoding:
            relative_position_bias = self.relative_position_bias_table_hi[
                self.relative_position_index[:N, :N].reshape(-1)].reshape(N, N, -1)  # Wd*Wh*Ww, Wd*Wh*Ww,nH
            attn = attn + relative_position_bias.permute(2, 0, 1).unsqueeze(0)  # B_, nH, N, N

        if mask is None:
            attn = self.softmax(attn)
        else:
            nW = mask.shape[0]
            attn = attn.view(B_ // nW, nW, self.hi_heads, N, N) + mask[:, :N, :N].unsqueeze(1).unsqueeze(0)
            attn = attn.view(-1, self.hi_heads, N, N)
            attn = self.softmax(attn)

        x = (attn @ v).transpose(1, 2).reshape(B_, N, C)

        return x

    def lo_attention(self, q, k, v, mask, x_shape, relative_position_encoding=True):
        B_, N, C = x_shape
        attn = (q * self.scale) @ k.transpose(-2, -1) # N*(N//4)
        
        _, ws1, ws2 = self.window_size
        ws0 = N//ws1//ws2

        if relative_position_encoding:
            relative_position_bias = self.relative_position_bias_table_lo[
                self.relative_position_index[:N, :N].reshape(-1)].reshape(N, ws0, ws1, ws2, -1)  # Wd*Wh*Ww, Wd*Wh*Ww,nH
            relative_position_bias_copy = relative_position_bias[:,:,::2,::2,:].reshape(N, N//4, -1)
            attn = attn + relative_position_bias_copy.permute(2, 0, 1).unsqueeze(0)  # B_, nH, N, N

        if mask is None:
            attn = self.softmax(attn)
        else:
            nW = mask.shape[0]
            mask = mask.reshape(nW, N, ws0, ws1, ws2)
            mask_copy = mask[:,:,:,::2,::2].reshape(nW,N,N//4)
            attn = attn.view(B_ // nW, nW, self.lo_heads, N, N//4) + mask_copy[:, :N, :N//4].unsqueeze(1).unsqueeze(0)
            attn = attn.view(-1, self.lo_heads, N, N//4)
            attn = self.softmax(attn)

        x = (attn @ v).transpose(1, 2).reshape(B_, N, C)

        return x

    def g_attention(self, q, k, v, mask, x_shape, relative_position_encoding=True):
        B_, N, C = x_shape
        attn = (q * self.scale) @ k.transpose(-2, -1)

        if relative_position_encoding:
            relative_position_bias = self.relative_position_bias_table_g[
                self.relative_position_index[:N, :N].reshape(-1)].reshape(N, N, -1)  # Wd*Wh*Ww, Wd*Wh*Ww,nH
            attn = attn + relative_position_bias.permute(2, 0, 1).unsqueeze(0)  # B_, nH, N, N

        if mask is None:
            attn = self.softmax(attn)
        else:
            nW = mask.shape[0]
            attn = attn.view(B_ // nW, nW, self.g_heads, N, N) + mask[:, :N, :N].unsqueeze(1).unsqueeze(0)
            attn = attn.view(-1, self.g_heads, N, N)
            attn = self.softmax(attn)

        x = (attn @ v).transpose(1, 2).reshape(B_, N, C)

        return x

    def get_position_index(self, window_size):
        ''' Get pair-wise relative position index for each token inside the window. '''

        coords_d = torch.arange(window_size[0])
        coords_h = torch.arange(window_size[1])
        coords_w = torch.arange(window_size[2])
        coords = torch.stack(torch.meshgrid(coords_d, coords_h, coords_w))  # 3, Wd, Wh, Ww
        coords_flatten = torch.flatten(coords, 1)  # 3, Wd*Wh*Ww
        relative_coords = coords_flatten[:, :, None] - coords_flatten[:, None, :]  # 3, Wd*Wh*Ww, Wd*Wh*Ww
        relative_coords = relative_coords.permute(1, 2, 0).contiguous()  # Wd*Wh*Ww, Wd*Wh*Ww, 3
        relative_coords[:, :, 0] += window_size[0] - 1  # shift to start from 0
        relative_coords[:, :, 1] += window_size[1] - 1
        relative_coords[:, :, 2] += window_size[2] - 1

        relative_coords[:, :, 0] *= (2 * window_size[1] - 1) * (2 * window_size[2] - 1)
        relative_coords[:, :, 1] *= (2 * window_size[2] - 1)
        relative_position_index = relative_coords.sum(-1)  # Wd*Wh*Ww, Wd*Wh*Ww

        return relative_position_index

    def get_sine_position_encoding(self, HW, num_pos_feats=64, temperature=10000, normalize=False, scale=None):
        """ Get sine position encoding """

        if scale is not None and normalize is False:
            raise ValueError("normalize should be True if scale is passed")

        if scale is None:
            scale = 2 * math.pi

        not_mask = torch.ones([1, HW[0], HW[1]])
        y_embed = not_mask.cumsum(1, dtype=torch.float32)
        x_embed = not_mask.cumsum(2, dtype=torch.float32)
        if normalize:
            eps = 1e-6
            y_embed = y_embed / (y_embed[:, -1:, :] + eps) * scale
            x_embed = x_embed / (x_embed[:, :, -1:] + eps) * scale

        dim_t = torch.arange(num_pos_feats, dtype=torch.float32)
        dim_t = temperature ** (2 * (dim_t // 2) / num_pos_feats)

        # BxCxHxW
        pos_x = x_embed[:, :, :, None] / dim_t
        pos_y = y_embed[:, :, :, None] / dim_t
        pos_x = torch.stack((pos_x[:, :, :, 0::2].sin(), pos_x[:, :, :, 1::2].cos()), dim=4).flatten(3)
        pos_y = torch.stack((pos_y[:, :, :, 0::2].sin(), pos_y[:, :, :, 1::2].cos()), dim=4).flatten(3)
        pos_embed = torch.cat((pos_y, pos_x), dim=3).permute(0, 3, 1, 2)

        return pos_embed.flatten(2).permute(0, 2, 1).contiguous()


class TMSA(nn.Module):

    def __init__(self,
                 dim,
                 input_resolution,
                 num_heads,
                 window_size=(6, 8, 8),
                 shift_size=(0, 0, 0),
                 mut_attn=True,
                 mlp_ratio=2.,
                 qkv_bias=True,
                 qk_scale=None,
                 drop_path=0.,
                 act_layer=nn.GELU,
                 norm_layer=nn.LayerNorm,
                 use_checkpoint_attn=False,
                 use_checkpoint_ffn=False
                 ):
        super().__init__()
        self.dim = dim
        self.input_resolution = input_resolution
        self.num_heads = num_heads
        self.window_size = window_size
        self.shift_size = shift_size
        self.use_checkpoint_attn = use_checkpoint_attn
        self.use_checkpoint_ffn = use_checkpoint_ffn

        assert 0 <= self.shift_size[0] < self.window_size[0], "shift_size must in 0-window_size"
        assert 0 <= self.shift_size[1] < self.window_size[1], "shift_size must in 0-window_size"
        assert 0 <= self.shift_size[2] < self.window_size[2], "shift_size must in 0-window_size"

        self.norm1 = norm_layer(dim)
        self.attn = WindowAttention(dim, window_size=self.window_size, num_heads=num_heads, qkv_bias=qkv_bias,
                                    qk_scale=qk_scale, mut_attn=mut_attn)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()
        self.norm2 = norm_layer(dim)
        self.mlp = Mlp_GEGLU(in_features=dim, hidden_features=int(dim * mlp_ratio), act_layer=act_layer)

    def forward_part1(self, x, mask_matrix):
        B, D, H, W, C = x.shape
        window_size, shift_size = get_window_size((D, H, W), self.window_size, self.shift_size)

        x = self.norm1(x)

        # pad feature maps to multiples of window size
        pad_l = pad_t = pad_d0 = 0
        pad_d1 = (window_size[0] - D % window_size[0]) % window_size[0]
        pad_b = (window_size[1] - H % window_size[1]) % window_size[1]
        pad_r = (window_size[2] - W % window_size[2]) % window_size[2]
        x = F.pad(x, (0, 0, pad_l, pad_r, pad_t, pad_b, pad_d0, pad_d1), mode='constant')

        _, Dp, Hp, Wp, _ = x.shape
        # cyclic shift
        if any(i > 0 for i in shift_size):
            shifted_x = torch.roll(x, shifts=(-shift_size[0], -shift_size[1], -shift_size[2]), dims=(1, 2, 3))
            attn_mask = mask_matrix
        else:
            shifted_x = x
            attn_mask = None

        # partition windows
        x_windows = window_partition(shifted_x, window_size)  # B*nW, Wd*Wh*Ww, C

        shifted_x_resize = shifted_x.reshape(-1,shifted_x.shape[2],shifted_x.shape[3],shifted_x.shape[4]).permute(0,3,1,2)
        ratio=4
        if (shifted_x.shape[2]//window_size[1])<=ratio:
            shifted_x_resize = F.interpolate(shifted_x_resize, size=(window_size[1],window_size[2]), mode='bilinear').permute(0,2,3,1)
            shifted_x_resize = shifted_x_resize.reshape(shifted_x.shape[0],shifted_x.shape[1],shifted_x_resize.shape[1],shifted_x_resize.shape[2],shifted_x_resize.shape[3])
            x_resize_windows = window_partition(shifted_x_resize, window_size).unsqueeze(1)
            x_resize_windows = x_resize_windows.expand(x_resize_windows.shape[0],x_windows.shape[0]//x_resize_windows.shape[0],x_resize_windows.shape[2],x_resize_windows.shape[3])
            x_resize_windows = x_resize_windows.reshape(-1,x_resize_windows.shape[2],x_resize_windows.shape[3])
        else:
            #scale = 3
            scale = 2
            nb3w_x = torch.zeros_like(shifted_x_resize).cuda()
            h = nb3w_x.shape[2]
            w = nb3w_x.shape[3]
            h_resize = int(h/scale)
            w_resize = int(w/scale)
            shifted_x_d3 = F.interpolate(shifted_x_resize, size=(h_resize,w_resize), mode='bilinear')
            win_h = window_size[1]
            win_w = window_size[2]
            win_h_resize = win_h/scale
            win_w_resize = win_w/scale
            for m in range(h // win_h):
                for n in range(w // win_w):
                    if m == 0:
                        h_start = 0
                        h_end = h_start + win_h
                    elif m == (h // win_h):
                        h_end = h_resize
                        h_start = h_end - win_h
                    else:
                        h_start = int((m+0.5)*win_h_resize)-win_h//2
                        h_end = h_start + win_h
                    if h_end>h_resize:
                        h_end = h_resize
                        h_start = h_end - win_h
                    
                    if n == 0:
                        w_start = 0
                        w_end = w_start + win_w
                    elif n == (w // win_w):
                        w_end = w_resize
                        w_start = w_end - win_w
                    else:
                        w_start = int((n+0.5)*win_w_resize)-win_w//2
                        w_end = w_start + win_w
                    if w_end>w_resize:
                        w_end = w_resize
                        w_start = w_end - win_w
                    nb3w_x[:,:,m*win_h:(m+1)*win_h,n*win_w:(n+1)*win_w] = shifted_x_d3[:,:,h_start:h_end,w_start:w_end]
            nb3w_x = nb3w_x.permute(0,2,3,1)
            nb3w_x = nb3w_x.reshape(shifted_x.shape[0],shifted_x.shape[1],nb3w_x.shape[1],nb3w_x.shape[2],nb3w_x.shape[3])
            x_resize_windows = window_partition(nb3w_x, window_size).unsqueeze(1)
            x_resize_windows = x_resize_windows.expand(x_resize_windows.shape[0],x_windows.shape[0]//x_resize_windows.shape[0],x_resize_windows.shape[2],x_resize_windows.shape[3])
            x_resize_windows = x_resize_windows.reshape(-1,x_resize_windows.shape[2],x_resize_windows.shape[3])

        
        attn_windows = self.attn(x_windows, x_resize_windows, mask=attn_mask)  # B*nW, Wd*Wh*Ww, C

        # merge windows
        attn_windows = attn_windows.view(-1, *(window_size + (C,)))
        shifted_x = window_reverse(attn_windows, window_size, B, Dp, Hp, Wp)  # B D' H' W' C

        # reverse cyclic shift
        if any(i > 0 for i in shift_size):
            x = torch.roll(shifted_x, shifts=(shift_size[0], shift_size[1], shift_size[2]), dims=(1, 2, 3))
        else:
            x = shifted_x

        if pad_d1 > 0 or pad_r > 0 or pad_b > 0:
            x = x[:, :D, :H, :W, :]

        x = self.drop_path(x)

        return x

    def forward_part2(self, x):
        return self.drop_path(self.mlp(self.norm2(x)))

    def forward(self, x, mask_matrix):
        """ Forward function.

        Args:
            x: Input feature, tensor size (B, D, H, W, C).
            mask_matrix: Attention mask for cyclic shift.
        """

        # attention
        if self.use_checkpoint_attn:
            x = x + checkpoint.checkpoint(self.forward_part1, x, mask_matrix)
        else:
            x = x + self.forward_part1(x, mask_matrix)

        # feed-forward
        if self.use_checkpoint_ffn:
            x = x + checkpoint.checkpoint(self.forward_part2, x)
        else:
            x = x + self.forward_part2(x)

        return x


class TMSAG(nn.Module):

    def __init__(self,
                 dim,
                 input_resolution,
                 depth,
                 num_heads,
                 window_size=[6, 8, 8],
                 shift_size=None,
                 mut_attn=True,
                 mlp_ratio=2.,
                 qkv_bias=False,
                 qk_scale=None,
                 drop_path=0.,
                 norm_layer=nn.LayerNorm,
                 use_checkpoint_attn=False,
                 use_checkpoint_ffn=False
                 ):
        super().__init__()
        self.input_resolution = input_resolution
        self.window_size = window_size
        self.shift_size = list(i // 2 for i in window_size) if shift_size is None else shift_size

        # build blocks
        self.blocks = nn.ModuleList([
            TMSA(
                dim=dim,
                input_resolution=input_resolution,
                num_heads=num_heads,
                window_size=window_size,
                shift_size=[0, 0, 0] if i % 2 == 0 else self.shift_size,
                mut_attn=mut_attn,
                mlp_ratio=mlp_ratio,
                qkv_bias=qkv_bias,
                qk_scale=qk_scale,
                drop_path=drop_path[i] if isinstance(drop_path, list) else drop_path,
                norm_layer=norm_layer,
                use_checkpoint_attn=use_checkpoint_attn,
                use_checkpoint_ffn=use_checkpoint_ffn
            )
            for i in range(depth)])

    def forward(self, x):
        """ Forward function.

        Args:
            x: Input feature, tensor size (B, C, D, H, W).
        """
        # calculate attention mask for attention
        B, C, D, H, W = x.shape
        window_size, shift_size = get_window_size((D, H, W), self.window_size, self.shift_size)
        x = rearrange(x, 'b c d h w -> b d h w c')
        Dp = int(np.ceil(D / window_size[0])) * window_size[0]
        Hp = int(np.ceil(H / window_size[1])) * window_size[1]
        Wp = int(np.ceil(W / window_size[2])) * window_size[2]
        attn_mask = compute_mask(Dp, Hp, Wp, window_size, shift_size, x.device)

        for blk in self.blocks:
            x = blk(x, attn_mask)

        x = x.view(B, D, H, W, -1)
        x = rearrange(x, 'b d h w c -> b c d h w')

        return x

def transIII_1x1_kxk(k1, b1, k2, b2, groups):
    if groups == 1:
        k = F.conv2d(k2, k1.permute(1, 0, 2, 3))
        b = (k2 * b1.reshape(1, -1, 1, 1)).sum((1, 2, 3))+b2
        #print(k2 * b1.reshape(1, -1, 1, 1))
        b_upleft = (k2 * b1.reshape(1, -1, 1, 1))[:,:,1:,1:].sum((1, 2, 3))+b2
        b_up = (k2 * b1.reshape(1, -1, 1, 1))[:,:,1:,:].sum((1, 2, 3))+b2
        b_upright = (k2 * b1.reshape(1, -1, 1, 1))[:,:,1:,:-1].sum((1, 2, 3))+b2
        b_left = (k2 * b1.reshape(1, -1, 1, 1))[:,:,:,1:].sum((1, 2, 3))+b2
        b_right = (k2 * b1.reshape(1, -1, 1, 1))[:,:,:,:-1].sum((1, 2, 3))+b2
        b_downleft = (k2 * b1.reshape(1, -1, 1, 1))[:,:,:-1,1:].sum((1, 2, 3))+b2
        b_down = (k2 * b1.reshape(1, -1, 1, 1))[:,:,:-1,:].sum((1, 2, 3))+b2
        b_downright = (k2 * b1.reshape(1, -1, 1, 1))[:,:,:-1,:-1].sum((1, 2, 3))+b2

    return k, b, b_upleft, b_up, b_upright, b_left, b_right, b_downleft, b_down, b_downright

def inference_with_fusion_weight_bias(x, weight1, bias1, weight2, bias2):
    B, C, D, H, W = x.shape
    weight, b, b_upleft, b_up, b_upright, b_left, b_right, b_downleft, b_down, b_downright = transIII_1x1_kxk(weight1,bias1,weight2,bias2,1)
    #bias = b.clone().unsqueeze(0).unsqueeze(-1).unsqueeze(-1).expand(1, dim, H, W)
    bias = b.unsqueeze(0).unsqueeze(-1).unsqueeze(-1)*torch.ones((1,1,H,W)).cuda()
    bias[:,:,0,:] = b_up.unsqueeze(0).unsqueeze(-1)*torch.ones((1,1,W)).cuda()
    bias[:,:,-1,:] = b_down.unsqueeze(0).unsqueeze(-1)*torch.ones((1,1,W)).cuda()
    bias[:,:,:,0] = b_left.unsqueeze(0).unsqueeze(-1)*torch.ones((1,1,H)).cuda()
    bias[:,:,:,-1] = b_right.unsqueeze(0).unsqueeze(-1)*torch.ones((1,1,H)).cuda()
    bias[:,:,0,0] = b_upleft
    bias[:,:,0,-1] = b_upright
    bias[:,:,-1,0] = b_downleft
    bias[:,:,-1,-1] = b_downright

    y = F.conv2d(x.permute(0,2,1,3,4).reshape(-1,C,H,W), weight, torch.zeros_like(b), padding=1)+bias
    y = y.reshape(B, D, C, H, W).permute(0,2,1,3,4)
    
    return y

class RTMSA(nn.Module):

    def __init__(self,
                 dim,
                 input_resolution,
                 depth,
                 num_heads,
                 window_size,
                 mlp_ratio=2.,
                 qkv_bias=True,
                 qk_scale=None,
                 drop_path=0.,
                 norm_layer=nn.LayerNorm,
                 use_checkpoint_attn=False,
                 use_checkpoint_ffn=None
                 ):
        super(RTMSA, self).__init__()
        self.dim = dim
        self.input_resolution = input_resolution

        self.residual_group = TMSAG(dim=dim,
                                    input_resolution=input_resolution,
                                    depth=depth,
                                    num_heads=num_heads,
                                    window_size=window_size,
                                    mut_attn=False,
                                    mlp_ratio=mlp_ratio,
                                    qkv_bias=qkv_bias, qk_scale=qk_scale,
                                    drop_path=drop_path,
                                    norm_layer=norm_layer,
                                    use_checkpoint_attn=use_checkpoint_attn,
                                    use_checkpoint_ffn=use_checkpoint_ffn
                                    )

        self.linear = nn.Linear(dim, dim)
        self.conv = nn.Conv3d(dim, dim, kernel_size=(1, 3, 3), padding=(0, 1, 1))

    def forward(self, x):
        #return x + self.conv(self.linear(self.residual_group(x).transpose(1, 4)).transpose(1, 4))
        #B, C, D, H, W = x.shape
        out = self.residual_group(x)
        #out = F.conv2d(out.permute(0,2,1,3,4).reshape(-1,C,H,W), self.linear.weight.data.unsqueeze(-1).unsqueeze(-1), self.linear.bias.data)
        #out = F.conv2d(out, self.conv.weight.data[:,:,0,:,:], self.conv.bias.data, padding=1).reshape(B, D, C, H, W).permute(0,2,1,3,4)
        out = inference_with_fusion_weight_bias(out, 
                                                self.linear.weight.data.unsqueeze(-1).unsqueeze(-1),
                                                self.linear.bias.data,
                                                self.conv.weight.data[:,:,0,:,:],
                                                self.conv.bias.data)
        out = x + out
        return out

class Stage(nn.Module):

    def __init__(self,
                 in_dim,
                 dim,
                 input_resolution,
                 depth,
                 num_heads,
                 window_size,
                 mul_attn_ratio=0.75,
                 mlp_ratio=2.,
                 qkv_bias=True,
                 qk_scale=None,
                 drop_path=0.,
                 norm_layer=nn.LayerNorm,
                 pa_frames=2,
                 deformable_groups=16,
                 reshape=None,
                 max_residue_magnitude=10,
                 use_checkpoint_attn=False,
                 use_checkpoint_ffn=False
                 ):
        super(Stage, self).__init__()
        self.pa_frames = pa_frames

        # reshape the tensor
        if reshape == 'none':
            self.reshape = nn.Sequential(Rearrange('n c d h w -> n d h w c'),
                                         nn.LayerNorm(dim),
                                         Rearrange('n d h w c -> n c d h w'))
        elif reshape == 'down':
            self.reshape = nn.Sequential(Rearrange('n c d (h neih) (w neiw) -> n d h w (neiw neih c)', neih=2, neiw=2),
                                         nn.LayerNorm(4 * in_dim), nn.Linear(4 * in_dim, dim),
                                         Rearrange('n d h w c -> n c d h w'))
        elif reshape == 'up':
            self.reshape = nn.Sequential(Rearrange('n (neiw neih c) d h w -> n d (h neih) (w neiw) c', neih=2, neiw=2),
                                         nn.LayerNorm(in_dim // 4), nn.Linear(in_dim // 4, dim),
                                         Rearrange('n d h w c -> n c d h w'))

        self.residual_group1 = TMSAG(dim=dim,
                                     input_resolution=input_resolution,
                                     depth=int(depth * mul_attn_ratio),
                                     num_heads=num_heads,
                                     window_size=(2, window_size[1], window_size[2]),
                                     mut_attn=True,
                                     mlp_ratio=mlp_ratio,
                                     qkv_bias=qkv_bias,
                                     qk_scale=qk_scale,
                                     drop_path=drop_path,
                                     norm_layer=norm_layer,
                                     use_checkpoint_attn=use_checkpoint_attn,
                                     use_checkpoint_ffn=use_checkpoint_ffn
                                     )
        self.linear1 = nn.Linear(dim, dim)
        self.conv1 = nn.Conv3d(dim, dim, kernel_size=(1, 3, 3), padding=(0, 1, 1))

        self.residual_group2 = TMSAG(dim=dim,
                                     input_resolution=input_resolution,
                                     depth=depth - int(depth * mul_attn_ratio),
                                     num_heads=num_heads,
                                     window_size=window_size,
                                     mut_attn=False,
                                     mlp_ratio=mlp_ratio,
                                     qkv_bias=qkv_bias, qk_scale=qk_scale,
                                     drop_path=drop_path,
                                     norm_layer=norm_layer,
                                     use_checkpoint_attn=True,
                                     use_checkpoint_ffn=use_checkpoint_ffn
                                     )
        self.linear2 = nn.Linear(dim, dim)
        self.conv2 = nn.Conv3d(dim, dim, kernel_size=(1, 3, 3), padding=(0, 1, 1))

    def forward(self, x):
        x = self.reshape(x)
        out1 = self.residual_group1(x)
        #out1 = F.conv2d(out1.permute(0,2,1,3,4).reshape(-1,C,H,W), self.linear1.weight.data.unsqueeze(-1).unsqueeze(-1), self.linear1.bias.data)
        #out1 = F.conv2d(out1, self.conv1.weight.data[:,:,0,:,:], self.conv1.bias.data, padding=1).reshape(B, D, C, H, W).permute(0,2,1,3,4)
        out1 = inference_with_fusion_weight_bias(out1, 
                                                 self.linear1.weight.data.unsqueeze(-1).unsqueeze(-1),
                                                 self.linear1.bias.data,
                                                 self.conv1.weight.data[:,:,0,:,:],
                                                 self.conv1.bias.data)
        out1 = x + out1
        out2 = self.residual_group2(out1)
        #out2 = F.conv2d(out2.permute(0,2,1,3,4).reshape(-1,C,H,W), self.linear2.weight.data.unsqueeze(-1).unsqueeze(-1), self.linear2.bias.data)
        #out2 = F.conv2d(out2, self.conv2.weight.data[:,:,0,:,:], self.conv2.bias.data, padding=1).reshape(B, D, C, H, W).permute(0,2,1,3,4)
        out2 = inference_with_fusion_weight_bias(out2, 
                                                 self.linear2.weight.data.unsqueeze(-1).unsqueeze(-1),
                                                 self.linear2.bias.data,
                                                 self.conv2.weight.data[:,:,0,:,:],
                                                 self.conv2.bias.data)
        out2 = out1 + out2


        return out2

class RViDeformer_MergeReparametersInference(nn.Module):

    def __init__(self,
                 upscale=4,
                 in_chans=4,
                 out_chans=4,
                 img_size=[8, 64, 64],
                 window_size=[6, 8, 8],
                 depths=[8, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 4, 4],
                 indep_reconsts=[11, 12],
                 embed_dims=[120, 120, 120, 120, 120, 120, 120, 180, 180, 180, 180, 180, 180],
                 num_heads=[6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
                 mul_attn_ratio=0.75,
                 mlp_ratio=2.,
                 qkv_bias=True,
                 qk_scale=None,
                 drop_path_rate=0.2,
                 norm_layer=nn.LayerNorm,
                 spynet_path=None,
                 pa_frames=2,
                 deformable_groups=16,
                 recal_all_flows=False,
                 nonblind_denoising=False,
                 use_checkpoint_attn=False,
                 use_checkpoint_ffn=False,
                 no_checkpoint_attn_blocks=[],
                 no_checkpoint_ffn_blocks=[],
                 ):
        super().__init__()
        self.in_chans = in_chans
        self.out_chans = out_chans
        self.upscale = upscale
        self.pa_frames = pa_frames
        self.recal_all_flows = recal_all_flows
        self.nonblind_denoising = nonblind_denoising

        conv_first_in_chans = in_chans
        self.conv_first = nn.Conv3d(conv_first_in_chans, embed_dims[0], kernel_size=(1, 3, 3), padding=(0, 1, 1))

        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, sum(depths))]  # stochastic depth decay rule
        reshapes = ['none', 'down', 'down', 'down', 'up', 'up', 'up']
        scales = [1, 2, 4, 8, 4, 2, 1]
        use_checkpoint_attns = [False if i in no_checkpoint_attn_blocks else use_checkpoint_attn for i in
                                range(len(depths))]
        use_checkpoint_ffns = [False if i in no_checkpoint_ffn_blocks else use_checkpoint_ffn for i in
                               range(len(depths))]

        # stage 1- 7
        for i in range(7):
            setattr(self, f'stage{i + 1}',
                    Stage(
                        in_dim=embed_dims[i - 1],
                        dim=embed_dims[i],
                        input_resolution=(img_size[0], img_size[1] // scales[i], img_size[2] // scales[i]),
                        depth=depths[i],
                        num_heads=num_heads[i],
                        mul_attn_ratio=mul_attn_ratio,
                        window_size=window_size,
                        mlp_ratio=mlp_ratio,
                        qkv_bias=qkv_bias,
                        qk_scale=qk_scale,
                        drop_path=dpr[sum(depths[:i]):sum(depths[:i + 1])],
                        norm_layer=norm_layer,
                        pa_frames=pa_frames,
                        deformable_groups=deformable_groups,
                        reshape=reshapes[i],
                        max_residue_magnitude=10 / scales[i],
                        use_checkpoint_attn=use_checkpoint_attns[i],
                        use_checkpoint_ffn=use_checkpoint_ffns[i],
                        )
                    )

        # stage 8
        self.stage8 = nn.ModuleList(
            [nn.Sequential(
                Rearrange('n c d h w ->  n d h w c'),
                nn.LayerNorm(embed_dims[6]),
                nn.Linear(embed_dims[6], embed_dims[7]),
                Rearrange('n d h w c -> n c d h w')
            )]
        )
        for i in range(7, len(depths)):
            self.stage8.append(
                RTMSA(dim=embed_dims[i],
                      input_resolution=img_size,
                      depth=depths[i],
                      num_heads=num_heads[i],
                      window_size=[1, window_size[1], window_size[2]] if i in indep_reconsts else window_size,
                      mlp_ratio=mlp_ratio,
                      qkv_bias=qkv_bias, qk_scale=qk_scale,
                      drop_path=dpr[sum(depths[:i]):sum(depths[:i + 1])],
                      norm_layer=norm_layer,
                      use_checkpoint_attn=use_checkpoint_attns[i],
                      use_checkpoint_ffn=use_checkpoint_ffns[i]
                      )
            )

        self.norm = norm_layer(embed_dims[-1])
        self.conv_after_body = nn.Linear(embed_dims[-1], embed_dims[0])

        # reconstruction
        if self.pa_frames:
            if self.upscale == 1:
                self.conv_last = nn.Conv3d(embed_dims[0], out_chans, kernel_size=(1, 3, 3), padding=(0, 1, 1))
            else:
                num_feat = 64
                self.conv_before_upsample = nn.Sequential(
                    nn.Conv3d(embed_dims[0], num_feat, kernel_size=(1, 3, 3), padding=(0, 1, 1)),
                    nn.LeakyReLU(inplace=True))
                self.upsample = Upsample(upscale, num_feat)
                self.conv_last = nn.Conv3d(num_feat, out_chans, kernel_size=(1, 3, 3), padding=(0, 1, 1))
        else:
            num_feat = 64
            self.linear_fuse = nn.Conv2d(embed_dims[0]*img_size[0], num_feat, kernel_size=1 , stride=1)
            self.conv_last = nn.Conv2d(num_feat, out_chans , kernel_size=7 , stride=1, padding=0)

    def init_weights(self, pretrained=None, strict=True):
        """Init weights for models.

        Args:
            pretrained (str, optional): Path for pretrained weights. If given
                None, pretrained weights will not be loaded. Defaults: None.
            strict (boo, optional): Whether strictly load the pretrained model.
                Defaults to True.
        """
        if isinstance(pretrained, str):
            logger = get_root_logger()
            load_checkpoint(self, pretrained, strict=strict, logger=logger)
        elif pretrained is not None:
            raise TypeError(f'"pretrained" must be a str or None. '
                            f'But received {type(pretrained)}.')

    def reflection_pad2d(self, x, pad=1):
        """ Reflection padding for any dtypes (torch.bfloat16.

        Args:
            x: (tensor): BxCxHxW
            pad: (int): Default: 1.
        """

        x = torch.cat([torch.flip(x[:, :, 1:pad+1, :], [2]), x, torch.flip(x[:, :, -pad-1:-1, :], [2])], 2)
        x = torch.cat([torch.flip(x[:, :, :, 1:pad+1], [3]), x, torch.flip(x[:, :, :, -pad-1:-1], [3])], 3)
        return x

    def forward(self, x):
        # x: (N, D, C, H, W)

        # main network
        if self.pa_frames:

            x_lq = x.clone()

            if self.upscale == 1:
                x = self.conv_first(x.transpose(1, 2))
                x = x + self.conv_after_body(
                    self.forward_features(x).transpose(1, 4)).transpose(1, 4)
                x = self.conv_last(x).transpose(1, 2)
                return x + x_lq

    def forward_features(self, x):
        '''Main network for feature extraction.'''

        x1 = self.stage1(x)
        x2 = self.stage2(x1)
        x3 = self.stage3(x2)
        x4 = self.stage4(x3)
        x = self.stage5(x4)
        x = self.stage6(x + x3)
        x = self.stage7(x + x2)
        x = x + x1

        for layer in self.stage8:
            x = layer(x)

        x = rearrange(x, 'n c d h w -> n d h w c')
        x = self.norm(x)
        x = rearrange(x, 'n d h w c -> n c d h w')

        return x

